replicaCount: 1

image:
  repository: grafana/grafana
  tag: 9.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  protocol: TCP
  targetPort: 8080
  nodePort: 30088

ingress:
  enabled: false

persistence:
  enabled: false

config:
  datasources: {}
  dashboards: {}
