---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: control-plane
- role: control-plane  
  image: kindest/node:v1.26.0
- role: worker
  image: kindest/node:v1.25.3
- role: worker

networking:
  apiServerAddress: "172.18.0.1"
  podSubnet: "10.245.0.0/16"
...