context:
	kubectl cluster-info --context kind-cluster1764

create:
	kind create cluster --name cluster1764 --config cluster1764.yaml

install:
	brew install kind
	open -a Docker

clean:
	kind delete cluster --name cluster1764