---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
spec:
  type: NodePort
  selector:
    app: blackbox-exporter
  ports:
  - name: blackbox
    protocol: TCP
    port: 9115
    targetPort: 9115
    nodePort: 30115