apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog
        ports:
        - containerPort: 1025
        - containerPort: 8025

---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-smtp-service
spec:
  selector:
    app: mailhog
  type: NodePort
  ports:
    - port: 1025
      targetPort: 1025
      nodePort: 31025

---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
spec:
  selector:
    app: mailhog
  type: NodePort
  ports:
    - port: 8025
      targetPort: 8025
      nodePort: 30825