apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
      - name: mailer
        image: localhost:31005/mailer:latest
        ports:
        - containerPort: 8080
