---
- name: Add user to sudoers for passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%parallels ALL=\(ALL\)'
    line: 'parallels ALL=(ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: true
