INSERT INTO EMAILPROFILES (EMAILPROFILES_ID, NAME, TYPE) VALUES (2, 'Profile1764SnippetsCoded', 'smtp.classic');

INSERT INTO CLASSICSMTPEMAILPROFILES (
    PROFILEID,
    HOSTNAME,
    PORT,
    USESSLPORT,
    STARTTLSENABLED,
    USERNAME,
    PASSWORD,
    SMTPTIMEOUT,
    DEBUGMODEENABLED,
    SSLPROTOCOLS
) VALUES (
    2, -- PROFILEID: NUMERIC(18,0)
    'localhost', -- HOSTNAME: VARCHAR(4096)
    30025, -- PORT: INTEGER
    FALSE, -- USESSLPORT: BOOLEAN (0 interpreted as FALSE)
    FALSE, -- STARTTLSENABLED: BOOLEAN (0 interpreted as FALSE)
    NULL, -- USERNAME: VARCHAR(4096) (empty value interpreted as NULL)
    NULL, -- PASSWORD: VARCHAR(4096) (empty value interpreted as NULL)
    10000, -- SMTPTIMEOUT: NUMERIC(18,0)
    FALSE, -- DEBUGMODEENABLED: BOOLEAN (0 interpreted as FALSE)
    'TLSv1.2' -- SSLPROTOCOLS: VARCHAR(4096)
);
