---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/"
  labels:
    app: influxdb
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
    nodePort: 30086
...