---
- name: Router Information Draft
  hosts: mikrotik-devices
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: routeros
    ansible_user: admin
    ansible_password: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    # idempotent with custom module in lib/ but its quite raw
    - name: Set hostname
      routeros_set_hostname:
        hostname: router1764
        host: 172.16.176.134
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
...