replicaCount: 1

image:
  repository: mysql
  tag: "8.3"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3306

persistence:
  enabled: true
  size: 10Gi

mysqlRootPassword: rootpassword
mysqlDatabase: mydb
mysqlUser: user
mysqlPassword: password
