run:
	ansible-playbook passwordlessSudo.yml --user=parallels -i 10.211.55.7, --ask-become-pass

# Context: This snippet just adds the parallels user to the sudoers file for my local setup with Parallels.
