---
- name: configure VyOS
  hosts: vyos
  vars:
    ansible_connection: network_cli
    ansible_network_os: vyos
    ansible_user: vyos
    ansible_password: vyos
    snippet: 1764Snippets
  tasks:
    - name: Merge config with live config
      vyos.vyos.vyos_firewall_interfaces:
        config:
        - access_rules:
          - afi: ipv4
            rules:
            - name: INBOUND
              direction: in
            - name: OUTBOUND
              direction: out
            - name: LOCAL_NET_FILTER
              direction: local
          name: eth1
        state: merged
  
    # - name: Delete firewall interface
    #  vyos.vyos.vyos_firewall_interfaces:
    #    config:
    #    - name: eth1
    #    state: deleted

    - name: No ping rule
      vyos.vyos.vyos_firewall_rules:
        config:
          - afi: ipv4
            rule_sets:
              - name: ICMP_BLOCK_RULESET
                description: "Block ICMP echo requests"
                default_action: accept
                rules:
                  - number: 10
                    action: reject
                    description: "Reject ICMP echo-requests"
                    protocol: icmp
                    icmp:
                      type_name: echo-request
        state: merged

    # Just for demonstration - careful with disabling ICMP
    - name: eth0 no ping
      vyos.vyos.vyos_firewall_interfaces:
        config:
          - access_rules:
              - afi: ipv4
                rules: 
                  - name: ICMP_BLOCK_RULESET
                    direction: local
            name: eth0
        state: merged
...