apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-mysql.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30010
  selector:
    app: {{ include "helm-mysql.fullname" . }}
