# update inventory with ip of router
run:
	ansible-playbook -i ansible/inventory.ini ansible/mikrotik_set_hostname.yml

#prep:
#	/ip address add address=172.16.176.134/24 interface=ether1
#	ssh admin@172.16.176.134
#	export ANSIBLE_LIBRARY=ansible/lib